### PR TITLE
Addesld to main

### PR DESCRIPTION
**Pull request by austinHeisleyCook**
syncinf repis

### CODE REVIEW

**Comment by austinHeisleyCook** [comment]
This is awesome

**Comment by rodeone2** [comment]
Well I will have to add the Node Traversal Engine after all. I had tried without it but it limits the rendering ability. Guido's Grail Tkinter engine gave an idea to also use the HTML Parser also because without printing the outputs into the command line as print statements nothing is as fast as it honestly. So both soon will be added. I'm slow and sick too so hang in there.

**Comment by austinHeisleyCook** [comment]
That's awesoms

**Comment by austinHeisleyCook** [comment]
thata aweosm

**Pull request merged**
